### ISSUE TITLE
Ability to hold down G-keys

### ISSUE THREAD

**Issue by aurtzy** [zocker-160/keyboard-center#14]
Currently, pressing a G-key will always trigger its respective macro, which means that even if there is one key assigned, it's treated as a quick press rather than staying held down until the user releases the key, making holding down G-keys not possible. Is this feature something that might be planned for the future?

**Comment by zocker-160** [comment]
I have not planned this feature, but it is possible to implement, so I will put it on the TODO.

**Comment by zocker-160** [comment]
I know this issue has been open for a very long time and you probably forgot about it, but I finally found the time to work on this and implement it. So there you go. :laughing:

**Comment by aurtzy** [comment]
Sweet! I completely understand and appreciate all the work you've already done on this software.

Looks to function just fine on my end. Cheers.

**Comment by zocker-160** [comment]
Nice glad to hear!
