### ISSUE TITLE
Numpad keys on G815 can't be added to macro.

### ISSUE THREAD

**Issue by Aditeya** [zocker-160/keyboard-center#23]
If I try to add a key, from the numpad, on to the macro input box, nothing happens. It accepts `NumLock` but won't accept any keys from the numpad. I'm running this on Arch Linux with the bspwm TWM.

**Comment by zocker-160** [comment]
Can confirm, does not work for me too, I will look into it

**Comment by zocker-160** [comment]
Issue found, QT does interpret the keys on the numpad as modifiers (for whatever reason) and they therefore get ignored.
I will try to find a workaround and push an update.

**Comment by zocker-160** [comment]
I just pushed 0.1.26 which should solve this issue, can you confirm it working?

**Comment by Aditeya** [comment]
Yes, It works but it seems to accept multiple keys as input on the numpad (with numlock on and off). However, it only uses the last key entered when triggered.

**Comment by Aditeya** [comment]
additionally if I make a macro such type `123` from the numpad and the numlock is off then it triggers the alternate keys (ie `End`, `Down`, `Page Down`)

**Comment by zocker-160** [comment]
> Yes, It works but it seems to accept multiple keys as input on the numpad (with numlock on and off). However, it only uses the last key entered when triggered.

uuh I see, yes that is another bug which is a side effect of this (stupid) workaround for the numpad. will fix that

> additionally if I make a macro such type 123 from the numpad and the numlock is off then it triggers the alternate keys (ie End, Down, Page Down)

That is something I cannot influence or change. Keyboard Center does simulate the keypress as if you would physically press it. So it will behave depending on the state of the numlock.

**Comment by zocker-160** [comment]
oops did not mean to close it

**Comment by zocker-160** [comment]
pushed fix for the multiple keys issue as 0.1.27

the second issue is a wontfix, since I am simulating the physical button press and therefore cannot take the state of numlock into account.

**Comment by Aditeya** [comment]
Yep, it works as expected. Also to detect numlock state, you could use `numlockx`. However, it wouldn't work on wayland since it is a X11 program.

**Comment by zocker-160** [comment]
ok thanks for the feedback, will close this issue then.

> Also to detect numlock state, you could use numlockx. However, it wouldn't work on wayland since it is a X11 program.

Yes I know that there are multiple options to implement that, but I want to stay as desktop environment agnostic as possible, which is why I use the uinput and udev kernel modules instead of any X11 or Wayland based solution.

It would be possible to make the application aware of the numlock state, but that would add complexity that I frankly do not want to maintain :/.
