### ISSUE TITLE
Add option to disable notifications

### ISSUE THREAD

**Issue by Corionis** [zocker-160/keyboard-center#31]
I sometimes switch profiles often and the notification tool in Linux stacks-up each change. That makes notifications from other software less useful, such as a new email from Thunderbird.

It would be helpful to have an option to disable Keyboard Center notification of profile changes.

This is a relatively low priority and just a suggestion.

Thanks for the great software.

**Comment by zocker-160** [comment]
this looks like a duplicate of #28 

I added that option in 0.1.29, are you running an older version?

**Comment by Corionis** [comment]
Yes, my apologies. Didn't catch it in a (too) quick scan.
