### ISSUE TITLE
Ability to hide tray icon

### ISSUE THREAD

**Issue by Aditeya** [zocker-160/keyboard-center#33]
# Feature request to hide tray icon

The idea I have is to pass a flag like '--hide-tray-icon' or '--daemon-mode'. This flag would just run the program as a daemon and wouldn't launch any GUI or tray icon. Any instance thats started after wouldn't start because it'll check to see if the daemon is running. This way you can avoid multiple processes being spawned. 

It can be a setting advertised in the help menu or the README for power users who'd like to hide it. Additionally if anyone wants to change the settings, they can:
1. kill the process
2. start keyboard-center normally
3. do their changes
4. Start with the flag

**Comment by zocker-160** [comment]
Alright so I pushed a new version which implement something similar using a local unix socket. It is still a bit janky but it should work for the most part.

You now have a new CLI `--background-mode` flag, which will disable the tray icon. 

You should be able to reactivate the primary window / instance by just executing the application again, it should close the secondary instance and trigger the primary one.

Let me know if that is a usable solution for you.

**Comment by Aditeya** [comment]
Yup it works well. The background instance gets killed upon spawning a new normal instance. However, it doesn't stop you from spawning multiple background instances.

**Comment by zocker-160** [comment]
> However, it doesn't stop you from spawning multiple background instances.

Are you sure you can spawn multiple background instances? It should not be possible, at least I cannot reproduce that.

**Comment by Aditeya** [comment]
![2022-06-30+T17-29-09](https://user-images.githubusercontent.com/22963960/176671935-2cf1f0f9-23c2-4900-a7cb-1677118eb130.png)

The left window grep the process list for `keyboard-center`, then I spawn another instance. The right window I grep the process list for `keyboard-center` again. Both have the flags `--background-mode`.

**Comment by zocker-160** [comment]
it should look like this when trying to start a secondary instance:

![Screenshot_20220630_141838](https://user-images.githubusercontent.com/36563538/176675319-dbf3f154-94ad-4423-9e18-c2ffd650308a.png)

**Comment by Aditeya** [comment]
![2022-06-30+T18-54-08](https://user-images.githubusercontent.com/22963960/176688560-9624a5fb-2324-4004-95f2-6067d0263422.png)

Yup, its not working. I'm not sure whats causing it, but I think it might be caused by a permisson issue or a bug in QT / python. Also i got the normal instance running while the background instance was still there: 

![2022-06-30+T18-57-16](https://user-images.githubusercontent.com/22963960/176689805-d2626344-dd24-4d70-ac28-de715b82b066.png)

**Comment by zocker-160** [comment]
yeah that is weird....but I don't think there is much I can do sadly, at least nothing obvious with no error message.

Are you on Wayland?

**Comment by Aditeya** [comment]
No Xorg, if you have any ideas on how to debug lemme know

**Comment by zocker-160** [comment]
Could you try again with the latest version? (If you even still use it that is)

**Comment by Aditeya** [comment]
It didn't work :(
![image](https://user-images.githubusercontent.com/22963960/226077223-8fdf71ac-465a-45b2-9895-e7ea4106f17b.png)

this line https://github.com/zocker-160/keyboard-center/blob/88014fb267ead874fba125f5090b060ccddb8f48/src/main.py#L24

returns false on my system. Could it be due to a missing library?

**Comment by zocker-160** [comment]
The singleton detection creates a local Unix socket in `/tmp` to check if another instance is already running.

There is probably something weird going on that does not let one instance access the socket of the other. I might look into changing from a Unix Socket to a simple tcp one.

**Comment by Aditeya** [comment]
I just tried running it as root
![image](https://user-images.githubusercontent.com/22963960/226155768-b66ce61a-d4f1-4d61-8659-d0e19ffaa9a9.png)

It auto launches from `~/.xprofile`
Is there a better way to handle this? maybe systemd-service?

**Comment by zocker-160** [comment]
ok weird, looks like permission issues. Does a normal process not have write access to /tmp on your machine?

>  Is there a better way to handle this? maybe systemd-service?

No I am not going to go down the systemd rabbit hole again, there are good reasons why I moved away from that and switched to a tray icon.

**Comment by Aditeya** [comment]
> ok weird, looks like permission issues. Does a normal process not have write access to /tmp on your machine?

it does. What happens is programs launched in `.xprofile` have root permissions, but programs launched from shell/app-launcher will have the users permissons (assuming your default shell is your signed in user). 

so when I login in `keyboard-center --background-mode` is launched as root automatically. And when I run it normally, it can't detect because it doesn't have root permissions to read the unix socket. However, launching it as root works because it will have permission to read the socket.

**Comment by zocker-160** [comment]
> And when I run it normally, it can't detect because it doesn't have root permissions to read the unix socket. However, launching it as root works because it will have permission to read the socket.

It should not matter though, since `/tmp` should always have permissions set to 777, which means any process has full access.
It seems to be different on your system for some reason, as from my testing it did work running as normal user.

Can you check to what permissions your /tmp folder is set to?

**Comment by Aditeya** [comment]
`/tmp` is 777. but inside, the files, have different permissions.
![image](https://user-images.githubusercontent.com/22963960/226240072-b8bb8cf3-fe8b-4243-8ba1-88cfbbcc2b69.png)

**Comment by Aditeya** [comment]
It Works!!!

**Comment by zocker-160** [comment]
nice awesome, glad to hear!
