### ISSUE TITLE
Error during init of keyboard

### ISSUE THREAD

**Issue by stefexec** [zocker-160/keyboard-center#48]
Thanks for the great work although i am getting this error:

![init](https://github.com/zocker-160/keyboard-center/assets/95532179/97c7b7e8-fe15-4e59-8c99-3f8040d97415)

I have installed 

https://github.com/JSubelj/g910-gkey-macro-support

previously but it is currently disabled as i discovered your amazing softeware after ive already installed that one.
Could this be related? What information do you need from me?

I have a G910 Orion Spectrum

**Comment by zocker-160** [comment]
Please try a reboot and don't start `g910-gkey-macro-support`.

The error most likely is cause by the fact that `g910-gkey-macro-support` unloads the kernel driver which causes keyboard-center to not be able to find the keyboard generating the error above.

A reboot will re-enable the kernel driver and should make your keyboard detectable again.

**Comment by stefexec** [comment]
I love you.
