### ISSUE TITLE
Using Super Key as Custom Modifier Deletes All Settings

### ISSUE THREAD

**Issue by scott-carrion** [zocker-160/keyboard-center#54]
First of all, excellent project. It works great, and having this work nicely with OpenRGB makes for a seamless solution for complete control over my devices that is actually better in terms of quality and feature set than the official, bloated, Windows-only "software".

Here's the bug I found:
Attempting to use the super (Windows) key as a custom modifier for a macro results in the settings.yml file being completely deleted.

Using Debian Bookworm and i3 (with GNOME installed as well), keyboard-center version 1.0.5.

I don't know if this has anything to do with it, but I have a Logitech G815 keyboard.

![image](https://github.com/zocker-160/keyboard-center/assets/47091519/43896236-0d97-4923-98f7-7a9f444b7211)

**Comment by zocker-160** [comment]
oh god thanks for reporting, this is really bad, will fix asap.

The Window / Super key should not be allowed int the custom modifier in the first place as it is already under the primary modifiers under "Meta". 
Maybe I should rename that button to make it more clear.

**Comment by zocker-160** [comment]
fixed in 1.0.6

**Comment by scott-carrion** [comment]
Just wanted to confirm that this issue is indeed fixed in 1.0.6 (great turnaround time by the way!)

I retested and now see that the "Meta/Super" key is clearly labeled now, and that upon hovering over the button, it now reads "aka the Windows key".

Ignoring this and trying to use the Super (aka Windows) key as a custom modifier is correctly denied: Nothing happens when you press it.
