### ISSUE TITLE
Feature Request: Option to disable openrgb integration

### ISSUE THREAD

**Issue by Yaakoss** [zocker-160/keyboard-center#60]
Hi,

i use a tiling window manager (Qtile) with X11 and/or wayland. No login manager.
Keyboard center gets startet via a hook from Qtile. This works mostly but the issue is that openrgb often does not started correctly, so i have to restart keyboard center manually to get the profile loaded.
Instead i would prefer to be able to disable openrgb start from keyboard-center and start it manually instead.

Meanwhile i edited the code on my machine and commented the codelines out. Now i can start both separately.

**Comment by zocker-160** [comment]
I agree in general this would be a good option to have.

In your case though you only have to make sure that openRGB is started before keyboard-center, it will automatically connect to an already running instance.

**Comment by Sa-Kage** [comment]
I second this request. I guess this was done to make it possible to automatically switch OpenRGB profiles when swapping profiles on keyboard, but it also makes it impossible (at least for me) to apply profiles via OpenRGB to my G910.

**Comment by zocker-160** [comment]
I know it is not a pretty solution, but I just don't have the time to implement a proper settings page.
