### ISSUE TITLE
AUR keyboard-center2 broken

### ISSUE THREAD

**Issue by recallmenot** [zocker-160/keyboard-center#71]
Hi,
the MAKEPKG installs keyboard-center2 to `/opt/keyboard-center2` instead.
The .desktop file now leads nowhere.
Can only launch it by `keyboard-center2` but this expects the files in `/opt/keyboard-center`:
```
python3: can't open file '/opt/keyboard-center/main.py': [Errno 2] No such file or directory
```

Had to `ln -s /opt/keyboard-center2 /opt/keyboard-center`, then I can launch it by `keyboard-center2`.

**Comment by zocker-160** [comment]
ah damn yes, I will fix asap
